# File: .github/workflows/workflow.yml

on: push

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/20af4e0f-1435-43a8-be69-ab52b68f8022/resourceGroups/contoso-traders-rg1729124               
        scopes-ignore: |
          /subscriptions/20af4e0f-1435-43a8-be69-ab52b68f8022/resourceGroups/contoso-traders-rg1729124/providers/microsoft.authorization
